# Generated by Django 6.1.1 on 2026-09-27 06:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, help_text='Unique event ID assigned by the payment gateway.', max_length=255, unique=True)),
                ('provider_reference', models.CharField(db_index=True, help_text='Transaction reference to which this event relates.', max_length=255)),
                ('payload_hash', models.CharField(help_text='SHA-256 hash of the verified raw request body for audit trail.', max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'webhook event',
                'verbose_name_plural': 'webhook events',
                'db_table': 'webhook_events',
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('event_id',), name='unique_webhook_event_id')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique client-supplied idempotency key preventing duplicate payment attempts.', max_length=255, unique=True)),
                ('provider_reference', models.CharField(db_index=True, help_text='Unique transaction reference assigned by the payment gateway.', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='INITIATED', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Sequential attempt number for the associated booking.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'payment attempt',
                'verbose_name_plural': 'payment attempts',
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('idempotency_key',), name='unique_payment_idempotency_key'), models.UniqueConstraint(fields=('provider_reference',), name='unique_payment_provider_reference'), models.UniqueConstraint(fields=('booking', 'attempt_number'), name='unique_booking_attempt_number'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_payment_amount')],
            },
        ),
    ]
