# Generated by Django 6.1.1 on 2026-09-27 06:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCentre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'diagnostic centre',
                'verbose_name_plural': 'diagnostic centres',
                'db_table': 'diagnostic_centres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'diagnostic test',
                'verbose_name_plural': 'diagnostic tests',
                'db_table': 'diagnostic_tests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CentreTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, help_text='Authoritative offering price in INR.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='catalog.diagnosticcentre')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centre_offerings', to='catalog.diagnostictest')),
            ],
            options={
                'verbose_name': 'centre test offering',
                'verbose_name_plural': 'centre test offerings',
                'db_table': 'centre_tests',
                'ordering': ['test__name'],
                'constraints': [models.UniqueConstraint(fields=('centre', 'test'), name='unique_centre_test_offering'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='positive_centre_test_price')],
            },
        ),
    ]
