# Generated by Django 6.1.1 on 2026-09-27 06:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_at', models.DateTimeField(help_text='Timezone-aware appointment timestamp scheduled in the future.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Authoritative immutable price snapshot at the moment of booking.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic concurrency tracking version incremented on each transition.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.centretest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_bookings_user_created'), models.Index(fields=['appointment_at', 'status'], name='idx_bookings_appt_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_booking_amount')],
            },
        ),
    ]
